service:
  name: "Kafka Message"
  version: "1.2.2"
  address: ":3000"
profiler:
  enable: true
  listening: 0.0.0.0:6060
kafka:
  brokers: "127.0.0.1:9092"
  version: "2.3.0"
  group: "km-consumer"
  producer: false
  ssl:
    enable: false
    clientcertfile: "cert/client.cer.pem"
    clientkeyfile: "cert/client.key.pem"
    cacertfile: "cert/server.cer.pem"
contacts:
- name: "zhigang"
  email: "zhigang52110@sina.com"